### ISSUE TITLE
Task: Fix POST request

### ISSUE THREAD

**Issue by aryanjverma** [Allen-ISD-Computer-Science/REPO_AutomaticDifferentiation_2024#72] opened 2024-02-26 15:49 UTC
For the iOS app, fix the POST request to ensure that users can send input to our server and recieve output.
#38

**Comment by DragonflyRobotics** [comment] 2024-02-28 20:37
Duplicate of #43 and #57 which are now complete

**Closed as completed by DragonflyRobotics** 2024-02-28 20:37 UTC
Labels: sprint-13
